add query preview button
fivetran/dbt-language-server pull request #143
Opened 2022-06-03 19:50 UTC by pgrivachev

![image](https://user-images.githubusercontent.com/3650304/171940051-b58aa484-79d9-464b-9594-7cab2fcae64d.png)

2022-06-06 09:25 UTC, fivetran-dmitryboykov requested changes
Do we need to update docs? It is not evident that we have "Show query preview" button.

2022-06-06 09:25 UTC, fivetran-dmitryboykov commented on package.json
> +          "when": "editorLangId =~ /^sql$|^jinja-sql$|^sql-bigquery$/ && !editorReadonly"
May be we should rely on `file extension` rather that `editorLangId` ? Currently we support any adapter but some files could be marked as `postgres-sql` and so on.

2022-06-08 15:35 UTC, pgrivachev commented
> Do we need to update docs? It is not evident that we have "Show query preview" button.

We will specify this in release notes. And looks like such button is the default way to show similar preview for VS Code (for example Markdown preview has similar button), so I think we will not overdoing documentation with this, especially since we did not remove the old context menu button.

2022-06-08 21:41 UTC, fivetran-dmitryboykov approved these changes

2022-06-08 22:08 UTC, merged