Support snowflake client
fivetran/dbt-language-server pull request #731
Opened 2023-02-07 14:30 UTC by pgrivachev

2023-02-08 17:33 UTC, fivetran-dmitryboykov requested changes
Looks good.

2023-02-08 17:33 UTC, fivetran-dmitryboykov commented on server/src/snowflake/SnowflakeClient.ts
> +    throw new Error('Method not implemented.');
It is OK. But it seems that we don't catch this exception.

2023-02-09 08:24 UTC, pgrivachev commented on server/src/snowflake/SnowflakeClient.ts
> +    throw new Error('Method not implemented.');
We don't need to catch it.

2023-02-09 09:06 UTC, pgrivachev commented on server/src/snowflake/SnowflakeClient.ts
> +    throw new Error('Method not implemented.');
The method is not implemented yet and not used anywhere.

2023-02-09 10:34 UTC, fivetran-dmitryboykov commented on server/src/snowflake/SnowflakeClient.ts
> +    throw new Error('Method not implemented.');
Ok, just fix it later.

2023-02-09 10:34 UTC, fivetran-dmitryboykov approved these changes

2023-02-09 14:39 UTC, merged