add the ability to compile models inside dbt packages
fivetran/dbt-language-server pull request #84
Opened 2022-03-29 07:07 UTC by pgrivachev

2022-03-30 08:57 UTC, fivetran-dmitryboykov commented on server/src/DbtTextDocument.ts
> +        .replace('models.', '')
Models location could be overwritten in `dbt_project.yml`. Moreover models could be located in multiple directories. E.g. `source-paths: ["models", "other_models"]`.

2022-03-30 11:20 UTC, fivetran-dmitryboykov commented on e2e/projects/project-with-packages/.gitignore
> +dbt_packages
Please add `dbt_modules`.

2022-03-30 11:42 UTC, fivetran-dmitryboykov commented on server/src/DbtTextDocument.ts
> +        .replace('models.', '')
Let's think if it would be better to create separate utils function, e.g. `extractModelName`.

2022-03-30 11:43 UTC, fivetran-dmitryboykov commented on server/src/DbtTextDocument.ts
> +        .replace('models.', '')
`dbt_packages` and `dbt_modules` to consts?

2022-03-30 11:43 UTC, fivetran-dmitryboykov commented on client/src/ExtensionClient.ts
> +        if (oneLevelUpPath.endsWith('dbt_packages') || oneLevelUpPath.endsWith('dbt_modules')) {
`dbt_packages` and `dbt_modules` to consts?

2022-03-30 12:03 UTC, fivetran-dmitryboykov requested changes
Generally looks good. But which features will be available for dbt package models ?
Go to definition isn't working - we need to use proper package name for such models.

2022-03-30 14:19 UTC, pgrivachev commented
> Generally looks good. But which features will be available for dbt package models ? Go to definition isn't working - we need to use proper package name for such models.

Good point! Looks like I can fix it.

2022-04-02 22:00 UTC, fivetran-dmitryboykov requested changes
Looks good. Just some questions.

2022-04-03 07:08 UTC, pgrivachev commented on server/src/DbtTextDocument.ts
> +      const modelsFolder = new RegExp(`(${dbtRepository.modelPaths.join('|')}).`);
Oh yes, you're right, I think for now we can just assume that the models in the packages are located in the models folder.

2022-04-03 07:08 UTC, pgrivachev commented on server/src/DbtRepository.ts
> +  static readonly PACKAGES_INSTALL_PATH_FIELD = 'packages-install-path';
Thank you, I missed this.

2022-04-03 07:12 UTC, pgrivachev commented on server/src/DbtTextDocument.ts
> +      return filePath.replaceAll('/', '.').replace(startWithPackagesFolder, '').replace(modelsFolder, '').replace(/.sql$/, '');
Should be `package_name.examples.users`. At least it works for salesforce_source.tmp.stg_salesforce__user_tmp model in our test project.

2022-04-04 12:31 UTC, merged